version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_DATABASE: greeninvoice
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      env_file: .env
    links:
      - mongo
volumes:
  logvolume01: {}
